apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  type: NodePort  # Change to ClusterIP or LoadBalancer as needed
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 80   # Port on the container
      nodePort: 30080  # Optional: Only for NodePort (must be between 30000–32767)
